### PR TITLE
Fixes for fetching the catalog, thumbnails and a cooldown deadlock

### PR DESCRIPTION
**Pull request by dedeibel**
I used the library quite a bit and found and solved some issues I want to share. Please see the commits individually for better focus.

- Initialized thead.OP in GetCatalog just like when parsing the index for consistency
- Fixed getting the catalog
- Fixed thumbnail URL creation, all thumbs are now jpgs and t.4cdn.org is gone.
- Secured the cooldown channel and timer setting a mutex since there was a race condition between reading the cooldown timer value and setting the new value which could result in a deadlock.

### CODE REVIEW

**Comment by moshee** [comment]
Thanks for doing this! Do you mind if I transfer ownership of this repo to you? I initially wrote this package for essentially a joke and I haven't actually used it since.

**Comment by dedeibel** [comment]
Thanks for your trust in me. But please keep in mind that the dependent project was kind of a "joke" project too and helped me learning go. I have no real plans to actively work on it besides reacting to issues or PRs.

But in case this library will be unmaintained and you are not willing to accept PRs I would try take care of it until someone more ambitious appears. We could also share editor rights…

**Comment by moshee** [comment]
I don't intend to maintain as I don't expect I'll ever use it again. But, it would probably be a dick move to change the import path without warning. So I can add you as a contributor.

Anyways, regarding the PR: looks like CI is failing on one of the test cases, can you look into that?

**Comment by dedeibel** [comment]
4chan API seems to have changed their page numbers from 0 based to 1 based

**Pull request merged**
